package tk.kqstone.dedd;

import java.util.prefs.Preferences;

import tk.kqstone.dedd.setting.Settings;

/**
 * 常量类，根据语言设置初始化为中文或英文
 */
public class Constant {

    // 字段定义（非 final）
    public static String VERSION;
    public static String VERSION_NAME;
    public static String PROG_NAME;
    public static String PROG_NAME_ENG;
    public static String DEFAULT_SERVER;
    public static String PROJ_DIR;
    public static String PROJ_FILE_SUFFIX;
    public static String PROG_AUTHOR;
    public static String PROG_EMAIL;
    public static String EXPIRE_MESSAGE;
    public static String ACCEPT;
    public static String REFUSE;
    public static String USER_AGREEMENT;
    public static String MENU_FILE;
    public static String NEW;
    public static String SAVE;
    public static String READFROM;
    public static String EXIT;
    public static String MENU_ABOUT;
    public static String ABOUT;
    public static String CLOSE;
    public static String LOADPICT;
	public final static String EDITPICT = "编辑照片";
	public final static String MARKLIP = "标记唇线";
	public final static String MARKTEETH = "标记牙位";
	public static final String ADJUSTTEETH = "美学设计";
	public static final String EXPORTDESIGN = "导出设计";
    public static String TITLE_NEW_PROJ;
    public static String UNNAME;
    public static String SAVE_PATH;
    public static String OK;
    public static String CANCEL;
    public static String BASICINFO;
    public static String NAME;
    public static String GENDER;
    public static final String MALE = "男";
    public static final String FEMALE = "女";
    public static String AGE;
    public static String AGE_SUFFIX;
    public static String PHONE;
    public static String TITLE_DESIGN_SCHEME;
    public static String DATE;
    public static String DESIGN_LABEL;
    public static String COMPARE_LABEL;
    public static String TOOTH_SITE;
    public static String TOOTH_LENGTH;
    public static String TOOTH_RATIO;
    public static String AUTO_ADJUST;
    public static String STARTING;
    public static String INITIALIZE_UI;
    public static String CONFIRM_EXIT;
    public static String SAVING_DATA;
    public static String EXIT_ON_FINISH;
    public static String CONFIRM_CLOSE;
    public static String LOADING;
    public static String CONFIRM_SAVE;
    public static String IMPORT_IMAGE_FIRST;
    public static String CHECK_UPDATE;
    public static String UPDATE;
    public static String CURRENT_VERSION;
    public static String LATEST_VERSION;
    public static String UPDATE_PERCENT;
    public static String UPDATE_SUCCESS;
    public static String UPDATE_FAIL;
    public static String RETRY;
    public static String CHECK_UPDATE_STATE;
    public static String UPDATEABLE;
    public static String NO_UPDATE;
    public static String UNKNOW;
    public static String CHECKING;
    public static String CONNECT_FAIL;
    public static String MENU_EDIT;
    public static String REDO;
    public static String UNDO;
    public static String MENU_DESIGN;
    public static String RE_ADJUST;
	public static final String UNIFYPLAN = "平行合平面";
    public static String ROTATE_LEFT_90D;
    public static String ROTATE_RIGHT_90D;
    public static String CONNECTION_ERROR;
    public static String ERROR;
    public static String AUTO_ADJUSTING;
    public static String FINISH;
    public static String SHOW_CONTOUR;
    public static String SHOW_REAL;
    public static String SHOW_NONE;
    public static String TEETH_DETECTION;
    public static String AI_DETECTION;
    public static String EXPORT_DESIGN_TO_FILE;
    public static String SETTINGS;
    public static String FACE_ANALYSIS;
    public static String NOFACE_ERROR;
    public static String NOTOOTH_ERROR;

    // 静态初始化块，根据语言设置初始化字段
    static {
        String lang = Settings.getCurrentLanguage(); // 获取当前语言设置
        if ("zh".equals(lang)) {
            initializeChinese();
        } else if ("en".equals(lang)) {
            initializeEnglish();
        } else {
            throw new IllegalArgumentException("Unsupported language: " + lang);
        }
    }

    // 中文初始化
    private static void initializeChinese() {
        VERSION = "v3.6";
        VERSION_NAME = "版本";
        PROG_NAME = "数字化美学牙科分析与设计";
        PROG_NAME_ENG = "Digital Esthetic Dentistry Design System";
        DEFAULT_SERVER = "kqstone.myqnapcloud.com";
        PROJ_DIR = "DeddProjects";
        PROJ_FILE_SUFFIX = "depx";
        PROG_AUTHOR = "作者: Dr. Kqstone";
        PROG_EMAIL = "邮箱: kqstone@qq.com";
        EXPIRE_MESSAGE = "软件版本已过期，将不可继续使用，是否尝试更新？";
        ACCEPT = "接受";
        REFUSE = "拒绝";
        USER_AGREEMENT = "软件使用许可协议";
        MENU_FILE = "文件";
        NEW = "新建";
        SAVE = "保存";
        READFROM = "读取";
        EXIT = "退出";
        MENU_ABOUT = "关于";
        ABOUT = "关于软件";
        CLOSE = "关闭";
        LOADPICT = "载入照片";
        TITLE_NEW_PROJ = "新建设计";
        UNNAME = "未命名";
        SAVE_PATH = "存储路径: ";
        OK = "确定";
        CANCEL = "取消";
        BASICINFO = "基本信息";
        NAME = "姓名";
        GENDER = "性别";
        AGE = "年龄";
        AGE_SUFFIX = "岁";
        PHONE = "电话";
        TITLE_DESIGN_SCHEME = "设计方案";
        DATE = "日期";
        DESIGN_LABEL = "设计图示";
        COMPARE_LABEL = "对比图";
        TOOTH_SITE = "牙位";
        TOOTH_LENGTH = "冠长";
        TOOTH_RATIO = "宽长比";
        AUTO_ADJUST = "自动优化";
        STARTING = "启动中";
        INITIALIZE_UI = "初始化工作界面...";
        CONFIRM_EXIT = "数据未保存，是否保存数据后再退出？";
        SAVING_DATA = "保存数据中...";
        EXIT_ON_FINISH = "数据保存中，完成后退出！";
        CONFIRM_CLOSE = "数据未保存，确定关闭吗？";
        LOADING = "载入中...";
        CONFIRM_SAVE = "数据未保存，是否保存？";
        IMPORT_IMAGE_FIRST = "请先载入照片！";
        CHECK_UPDATE = "检查更新";
        UPDATE = "升级";
        CURRENT_VERSION = "当前版本：";
        LATEST_VERSION = "最新版本：";
        UPDATE_PERCENT = "升级进度：";
        UPDATE_SUCCESS = "升级成功，下次启动时将使用新版！";
        UPDATE_FAIL = "升级失败！";
        RETRY = "重试";
        CHECK_UPDATE_STATE = "检测新版本...";
        UPDATEABLE = "发现新版本，是否升级？";
        NO_UPDATE = "未发现新版本，无需升级！";
        UNKNOW = "未知";
        CHECKING = "检测中...";
        CONNECT_FAIL = "服务器连接失败，请检查网络连接！";
        MENU_EDIT = "编辑";
        REDO = "重做";
        UNDO = "撤销";
        MENU_DESIGN = "设计";
        RE_ADJUST = "重新设计";
        ROTATE_LEFT_90D = "向左旋转90°";
        ROTATE_RIGHT_90D = "向右旋转90°";
        CONNECTION_ERROR = "无法连接服务器，请重试!";
        ERROR = "错误";
        AUTO_ADJUSTING = "自动优化调整中...";
        FINISH = "完成";
        SHOW_CONTOUR = "显示轮廓";
        SHOW_REAL = "显示牙冠";
        SHOW_NONE = "隐藏显示";
        TEETH_DETECTION = "AI检测中...";
        AI_DETECTION = "AI检测";
        EXPORT_DESIGN_TO_FILE = "保存至文件";
        SETTINGS = "设置";
        FACE_ANALYSIS = "人脸分析";
        NOFACE_ERROR = "未检测到人脸，请手动调整";
        NOTOOTH_ERROR = "未检测到牙齿，请手动标注";
    }

    // 英文初始化
    private static void initializeEnglish() {
        VERSION = "v3.6";
        VERSION_NAME = "Version";
        PROG_NAME = "Digital Aesthetic Dental Analysis and Design";
        PROG_NAME_ENG = "Digital Esthetic Dentistry Design System";
        DEFAULT_SERVER = "kqstone.myqnapcloud.com";
        PROJ_DIR = "DeddProjects";
        PROJ_FILE_SUFFIX = "depx";
        PROG_AUTHOR = "Author: Dr. Kqstone";
        PROG_EMAIL = "Email: kqstone@qq.com";
        EXPIRE_MESSAGE = "This software version has expired. Would you like to check for updates?";
        ACCEPT = "Accept";
        REFUSE = "Decline";
        USER_AGREEMENT = "End User License Agreement";
        MENU_FILE = "File";
        NEW = "New";
        SAVE = "Save";
        READFROM = "Open";
        EXIT = "Exit";
        MENU_ABOUT = "About";
        ABOUT = "About";
        CLOSE = "Close";
        LOADPICT = "Load Image";
        TITLE_NEW_PROJ = "New Project";
        UNNAME = "Untitled";
        SAVE_PATH = "Save Path: ";
        OK = "OK";
        CANCEL = "Cancel";
        BASICINFO = "Basic Info";
        NAME = "Name";
        GENDER = "Gender";
        AGE = "Age";
        AGE_SUFFIX = " y/o";
        PHONE = "Phone";
        TITLE_DESIGN_SCHEME = "Design Scheme";
        DATE = "Date";
        DESIGN_LABEL = "Design Preview";
        COMPARE_LABEL = "Comparison";
        TOOTH_SITE = "id";
        TOOTH_LENGTH = "len";
        TOOTH_RATIO = "W/L";
        AUTO_ADJUST = "Auto Optimize";
        STARTING = "Starting...";
        INITIALIZE_UI = "Initializing workspace...";
        CONFIRM_EXIT = "Unsaved changes detected. Save before exiting?";
        SAVING_DATA = "Saving data...";
        EXIT_ON_FINISH = "Exiting after save completes!";
        CONFIRM_CLOSE = "Unsaved changes will be lost. Confirm close?";
        LOADING = "Loading...";
        CONFIRM_SAVE = "Save unsaved changes?";
        IMPORT_IMAGE_FIRST = "Please load an image first!";
        CHECK_UPDATE = "Check for Updates";
        UPDATE = "Update";
        CURRENT_VERSION = "Current Version: ";
        LATEST_VERSION = "Latest Version: ";
        UPDATE_PERCENT = "Progress: ";
        UPDATE_SUCCESS = "Update successful! New version will take effect after restart.";
        UPDATE_FAIL = "Update failed!";
        RETRY = "Retry";
        CHECK_UPDATE_STATE = "Checking for updates...";
        UPDATEABLE = "New version available. Update now?";
        NO_UPDATE = "You're using the latest version.";
        UNKNOW = "Unknown";
        CHECKING = "Checking...";
        CONNECT_FAIL = "Connection failed. Check network and retry!";
        MENU_EDIT = "Edit";
        REDO = "Redo";
        UNDO = "Undo";
        MENU_DESIGN = "Design";
        RE_ADJUST = "Redesign";
        ROTATE_LEFT_90D = "Rotate Left 90°";
        ROTATE_RIGHT_90D = "Rotate Right 90°";
        CONNECTION_ERROR = "Server connection error!";
        ERROR = "Error";
        AUTO_ADJUSTING = "Auto-optimizing...";
        FINISH = "Complete";
        SHOW_CONTOUR = "Show Contour";
        SHOW_REAL = "Show Crown";
        SHOW_NONE = "Hide Display";
        TEETH_DETECTION = "AI Detecting...";
        AI_DETECTION = "AI Detection";
        EXPORT_DESIGN_TO_FILE = "Export to File";
        SETTINGS = "Settings";
        FACE_ANALYSIS = "Facial Analysis";
        NOFACE_ERROR = "No face detected. Manual adjustment required.";
        NOTOOTH_ERROR = "No teeth detected. Manual marking required.";
    }
}